# _config.yml

# Site settings
title: Raycyril Estillore - Data Scientist & Analyst
description: "Passionate in analyzing data and proficient in communication to help with your business needs."

# Author information
author:
  name: Raycyril Estillore
  bio: "Data Scientist | Data Analyst | Passionate in analyzing data and proficient in communication to help with your business needs."
  email: raycyril88@gmail.com
  github: raycyril88.github.io
  linkedin: https://www.linkedin.com/in/raycyril-estillore/
  avatar: "/assets/img/my_pic.png"  # Specify the path to your profile picture

# Build settings
markdown: kramdown
theme: minima

# Navigation links
header_pages:
  - Home: /

# Social links
social_icons:
  - title: GitHub
    url: https://github.com/your_github_handle
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://linkedin.com/in/your_linkedin_profile
    icon: fab fa-linkedin

# About Me section
about_me: |
  I am Raycyril Estillore. I've been employed by BARK for more than two years. As a senior subject matter expert for the organization, my current responsibility is to support customer care personnel. I frequently work with the Customer Insights Analyst and Peer Support teams to find ways to address customer complaints and streamline processes. I pay close attention to details and have excellent analytical abilities. I am skilled in Python-based statistical data analysis, creating PowerBI dashboards and data models, SQL, Excel, and constructing reports.

  Looking forward to working with you!

# Skills section
skills:
  hard_skills:
    - Excel
    - SQL
    - PowerBI
    - Tableau
    - Python
    - Google Workspace
    - Shopify
    - ZenDesk
    - Salesforce
  soft_skills:
    - Data Analysis, Cleaning & Visualization
    - Strong Communication
    - Attention to Detail
    - Great Interpersonal Skills
  advanced_skills:
    - Machine Learning
    - Correlation Analysis
    - Regression Analysis
    - Time Series Analysis
    - Anomaly Detection
    - Hypothesis Testing
    - RFM Analysis
    - Cohort Analysis
    - Financial Viability Metrics
    - Customer Satisfaction Metrics
    - Online Capability Metrics
    - Project Management
    - Data Science and Analytics
    - Finance and Risk
